---
# Config file to specify themes with css color variables, as well as other template setup
# Under apts:, specify tags, names, starting code, optional description, and more
setup:
    title: "CompSci 101, Fall 2021 APTs"
    desc: "This is the webpage for grading and submitting your APTs."
    theme:
        accent: "#012a4a"
        text: "black"
        text_inv: "white"
        back: "#d3dceb"
        section: "rgba(242,242,242,1)"
        section_f: "rgba(0,0,0,0.05)"
        correct: "rgba(0, 179, 0, 1)"
        wrong: "rgba(255, 17, 0, 1)"
        correct_l: "rgba(0, 179, 0, .2)"
        wrong_l: "rgba(255, 17, 0, .23)"
        progress: "rgb(255, 224, 75)"

apts:
  - section_:
    - name: "DivToZero"
      desc: "required, helper function useful, in Lecture 12"
      tags:
        - Lecture 12
        - Required
        - PS 1


    {
        id: "1",
        name: "Problem Set 1",
        info: "APT-2, Due on 9/28, Complete all five of them.",
        apts: [
            {
                name: "DivToZero",
                description: "required, helper function useful, in Lecture 12",
                status: "correct",
                tags:[ 'Lecture 12', 'Required'],
            },
            {
                name: "Yahtzee",
                description: "",
                status: "correct",
                tags:[]
            },
            {
                name: "OneHeapNim",
                description: "",
                status: "wrong",
                tags:[]
            },
            {
                name: "HingedDoor",
                description: "",
                status: "",
                tags:['Required']
            },
            {
                name: "Pancakes",
                description: "",
                status: "whateve",
                tags:['Required']
            },
        ]
    },
    {
        id: "2",
        name: "Problem Set 2",
        info: "APT-4, Due on Oct 19, Complete 5 - Two are required, plus three more, the others are extra.",
        apts: [
            {
                name: "IsSpecial",
                description: "",
                status: "correct",
                tags:[]
            },
            {
                name: "MorseLikeCode",
                description: "Lab 05, parallel lists",
                status: "correct",
                tags:['Lab 05', 'Parallel Lists']
            },
            {
                name: "Pikachu",
                description: "while loop maybe",
                status: "wrong",
                tags:['While Loop']
            },
            {
                name: "Calculator",
                description: "",
                status: "",
                tags:['Required']
            },
            {
                name: "Family",
                description: "Challenge, in Lecture 13",
                status: "whateve",
                tags:['Challenge', 'Lecture 13']
            },
            {
                name: "TxMsg",
                description: "required, helper function useful, in Lecture 12",
                status: "wrong",
                tags:['Required', 'Lecture 12']
            },
            {
                name: "ScoreIt",
                description: "required, helper function useful",
                status: "correct",
                tags:['Required', 'Lecture 12']
            },
        ]
    },
    {
        id: "3",
        name: "Problem Set 2",
        info: "APT-4, Due on Oct 19, Complete 5 - Two are required, plus three more, the others are extra.",
        apts: [
            {
                name: "IsSpecial",
                description: "",
                status: "correct",
                tags:[]
            },
            {
                name: "MorseLikeCode",
                description: "Lab 05, parallel lists",
                status: "correct",
                tags:['Lab 05', 'Parallel Lists']
            },
            {
                name: "Pikachu",
                description: "while loop maybe",
                status: "wrong",
                tags:['While Loop']
            },
            {
                name: "Calculator",
                description: "",
                status: "",
                tags:['Required']
            },
            {
                name: "Family",
                description: "Challenge, in Lecture 13",
                status: "whateve",
                tags:['Challenge', 'Lecture 13']
            },
            {
                name: "TxMsg",
                description: "required, helper function useful, in Lecture 12",
                status: "wrong",
                tags:['Required', 'Lecture 12']
            },
            {
                name: "ScoreIt",
                description: "required, helper function useful",
                status: "correct",
                tags:['Required', 'Lecture 12']
            },
        ]
    },

];
