---
# Config file to specify themes with css color variables, as well as other template setup
# Under theme: each variable corresponds with a CSS variable. Thus, all values you enter should be valid css colors (hex,rgb,"red",etc.)
# Under apts:, specify tags, names, starting code, optional description, and more
setup:
    title: "CompSci 101, Fall 2021 APTs"
    desc: "This is the webpage for grading and submitting your APTs."
    theme:
        accent: "#012a4a"
        text: "black"
        text_inv: "white"
        back: "#d3dceb"
        section: "rgba(242,242,242,1)"
        section_f: "rgba(0,0,0,0.05)"
        correct: "rgba(0, 179, 0, 1)"
        wrong: "rgba(255, 17, 0, 1)"
        correct_l: "rgba(0, 179, 0, .2)"
        wrong_l: "rgba(255, 17, 0, .23)"
        progress: "rgb(255, 224, 75)"
